version: '2'
services:
  minigo:
    build: .
    container_name: mojapp
    ports:
      - 8898:8898
      - 8888:8888
    depends_on:
      - cassandra
    networks:
       - mojnetwork
    
  cassandra: 
    image: "cassandra:3.11"
    ports:
      - '9042:9042'
    expose: 
      - 9042
    container_name: cassandra
    networks:
       - mojnetwork
networks:
  mojnetwork:
   


 
