version: '2'
services:
  minigo:
    build: .
    container_name: mojapp
    ports:
      - 8898:8898
    expose:
      - 8898
    depends_on:
      - cassandra
    networks:
       - mojnetwork
    
  cassandra: 
    image: "cassandra:3.11"
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    expose: 
      - 9042
    container_name: cassandra
    networks:
       - mojnetwork
networks:
  mojnetwork:
   


 
